### ISSUE TITLE
Unable to load images

### ISSUE THREAD

**Issue by LoneDevilX** [Andavin/Images#13]
The Plugins isn't loading the images and the usage command are different

https://pastebin.ubuntu.com/p/W97qfnw7p2/

**Comment by Andavin** [comment]
Hi,

This isn't a bug. The images cannot be loaded since the world no longer exists for where they were placed. A rewrite to the data management system is required in order to alter this behavior.

This is planned, but a simple fix is delete the images before deleting the world. If you already deleted the world then recreate it and use the delete near command to wipe all images and proceed from there.
