### ISSUE TITLE
Colour palette is very limited

### ISSUE THREAD

**Issue by seb303** [Andavin/Images#36]
I've tried both 24bit PNG and JPEG and always the image comes out in Minecraft (1.17.1 on PaperMC) looking like 8 bit colour.

An example:

The original:
![image](https://user-images.githubusercontent.com/467942/153725871-a641bc5e-bdf1-43c0-b988-a39d5f231752.png)

In Minecraft:
![image](https://user-images.githubusercontent.com/467942/153725860-611b2e10-f2bb-45af-b91c-6b9dbe5b5e5e.png)

Is this expected behaviour?  I though Minecraft supported 24bit colour.

**Comment by seb303** [comment]
P.S. This is Minecraft 1.17.1 on PaperMC

**Comment by Andavin** [comment]
This is expected behavior. Minecraft does support full color, but not on maps necessarily since they are only intending to show something like the tops of blocks (i.e. the different material colors). In a future release, there are a few things I can do that I think may improve it, but at the moment this is something that we just live with.
