### ISSUE TITLE
Large images cannot be deleted?

### ISSUE THREAD

**Issue by A-Words** [Andavin/Images#4]
I placed a picture with a resolution of 1118X1534, I can place it normally, but I cannot delete it in any way(even if I use / image delete or uninstall the plugin  ...).

**Comment by Andavin** [comment]
Do you have any addition info on this?
1. What does happen when you click on the image? 
2. What version of Spigot/Paper are you using?
3. What version of the plugin are you using?
4. Have you tested with smaller images and are you able to successfully delete them?
5. Are you running ProtocolLib?
6. Have you tested without any other plugins installed besides CustomImages and/or ProtocolLib?

**Comment by AliexVIII** [comment]
Second this. I can't remove an image I placed.
The plugin works great besides this. 
When you initiate the delete command and right click on the image, nothing happens.
If anything, I think the best thing to incorporate is a "delete all" or "delete last" command as a failsafe for this. Otherwise great plugin, I just got stuck with an image I placed poorly on my wall that can't be destroyed.

**Comment by Andavin** [comment]
> Second this. I can't remove an image I placed.
> The plugin works great besides this.
> When you initiate the delete command and right click on the image, nothing happens.
> If anything, I think the best thing to incorporate is a "delete all" or "delete last" command as a failsafe for this. Otherwise great plugin, I just got stuck with an image I placed poorly on my wall that can't be destroyed.

I'd recommend installing ProtocolLib and see if it makes a difference and hopefully report back. ProtocolLib tends to have a much higher reliability than the built in packet listener for some reason.
